# For Demo
POST  http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username": "Demo",
    "password": "demo",
    "email": "demo@gmail.com",
    "name": "demo"
}

###

# For Demo
POST  http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "demo@gmail.com",
    "password": "demo"
}

###
